# -*- mode: ruby -*-
# vi: set ft=ruby :

box_name = "tl-ubuntu-1604-64bit-60gb"

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true
  config.vm.provider :virtualbox do |provider, override|
    provider.name = box_name
    override.vm.box = box_name + ".box"
    override.vm.box_url = ["file://" + box_name + ".box", "terminal-labs/" + box_name]
    provider.customize ['modifyvm', :id, '--nictype1', 'virtio']
  end
end
