# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true
  config.vm.provider :virtualbox do |provider, override|
    provider.name = "tl_ubuntu_1404_64bit_40gb"
    override.vm.box = "tl_ubuntu_1404_64bit_40gb"  
    override.vm.box_url = "https://s3-us-west-1.amazonaws.com/terminal-labs-vagrant-boxes/tl_ubuntu_1404_64bit_40gb.box"
    provider.customize ['modifyvm', :id, '--nictype1', 'virtio'] 
  end
end
