# -*- mode: ruby -*-
# vi: set ft=ruby :

dirname = File.basename(Dir.getwd)
box_name = dirname

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.ssh.forward_agent = true
  config.vm.provider :virtualbox do |provider, override|
    provider.name = box_name
    override.vm.box = box_name + ".box"
    override.vm.box_url = "file://../../../builds/" + box_name + ".box"
    provider.customize ['modifyvm', :id, '--nictype1', 'virtio']
  end
end
