# -*- mode: ruby -*-
# vi: set ft=ruby :

box_name = "tl-debian-jessie-64bit-2tb"

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true
  config.vm.provider :virtualbox do |provider, override|
    provider.name = box_name
    override.vm.box = box_name + ".box"
    override.vm.box_url = ["file://" + box_name + ".box"]
    provider.customize ['modifyvm', :id, '--nictype1', 'virtio']
    provider.customize ['modifyvm', :id, '--nictype2', 'virtio']
  end
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
end
