# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true
  config.vm.provider :virtualbox do |provider, override|
    provider.name = "tl_debian_jessie_64bit_2tb_gui"
    override.vm.box = "tl_debian_jessie_64bit_2tb_gui"  
    override.vm.box_url = "https://s3-us-west-1.amazonaws.com/terminal-labs-vagrant-boxes/tl_debian_jessie_64bit_2tb_gui.box"
    provider.customize ['modifyvm', :id, '--nictype1', 'virtio']
    provider.gui = true
  end
end
